#' A data.table containing methylation data
#' (position, number methylated reads and number of reads total)
#' This object contains reduced
#' representation bisulfite sequencing data from the
#' GM06990 B-lymphoblastoid cell line that was generated by the ENCODE
#' project (GEO accession GSE27584, sample GSM980583).
#' Only a subset of the full data is used in this object and the
#' data was switched from hg19 to hg38.
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleBSDT
#' @usage data(exampleBSDT)
#' @format A data.table, data.frame object
NULL

#' A named \code{list} of 4 \code{data.table} objects,
#' each of which has 10000 rows containing 5 columns of
#' methylation data for a given sample:
#'\itemize{
#'    \item{chr} {chromosome of methylation read}
#'    \item{start} {starting position for methylation read}
#'    \item{methylCount} {number of methylated reads}
#'    \item{coverage} {number of reads total}
#'    \item{sampleName} {name of the particular sample}
#'    }
#'
#' @docType data
#' @keywords datasets
#' @name BSDTlist
#' @usage data(BSDTlist)
#' @format A list object
NULL
